### ISSUE TITLE
Wrong name for script in Guides for contributors > Workflow

### ISSUE THREAD

**Issue by michielcock** [homermultitext/hmt-web#26]
On http://www.homermultitext.org/hmt-docs/guides/workflow.html under 3 it reads "sh hmt-refresh.sh", but apparently the script is called refresh-hmt.sh, so it should read "sh refresh-hmt.sh" (at least, that was how I got it to work ...)

**Comment by StephanieML** [comment]
This issue can be closed.

**Comment by neelsmith** [comment]
done
